const fs = require('fs');
const path = require('path');

const assetsDir = path.join(__dirname, '..', 'assets', 'protocols');
const outFile = path.join(__dirname, '..', 'src', 'data', 'protocolAssets.ts');
const medsFile = path.join(__dirname, '..', 'src', 'data', 'medications.ts');

function normalizeName(name) {
  const ext = path.extname(name);
  const base = path.basename(name, ext);
  let safe = base.replace(/\s+/g, '_');
  safe = safe.replace(/[%#@!$&+,:;=<>?\\\/`~\[\]\(\)\-]/g, '');
  safe = safe.replace(/_+/g, '_');
  return safe + ext;
}

function walk(dir) {
  const results = [];
  const list = fs.readdirSync(dir, { withFileTypes: true });
  list.forEach((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walk(full));
    else if (entry.isFile()) results.push(full);
  });
  return results;
}

const files = walk(assetsDir).filter(f => /\.pdf$/i.test(f));

const rels = files.map(f => {
  const rel = path.relative(path.join(__dirname, '..', 'assets'), f).replace(/\\/g, '/');
  // rel starts with protocols/...
  const parts = rel.split('/');
  const folder = parts[1] || '';
  const fileName = parts.slice(2).join('/') || parts[1];
  return { full: f, rel, folder, fileName };
});

// Build protocolAssets content
let content = '// Auto-generated runtime map: pdfUrl -> required asset module\n';
content += "// Regenerated by scripts/generateProtocolAssets.js\n\n";
content += 'const protocolAssets: { [k: string]: any } = {\n';

rels.forEach(({ full, rel }) => {
  // rel e.g. protocols/Cardiac/C-1_AMI_Fibrinolytic_Checklist.pdf
  const parts = rel.split('/');
  const folder = parts[1];
  const file = parts.slice(2).join('/');
  // normalize filename using same function
  const norm = normalizeName(file);
  const pdfUrl = `/assets/protocols/${folder}/${norm}`;
  const requirePath = `../../assets/protocols/${folder}/${norm}`;
  content += `  "${pdfUrl}": require('${requirePath}'),\n`;
});

content += '};\n\nexport default protocolAssets;\n';

fs.writeFileSync(outFile, content, 'utf8');
console.log('Wrote', outFile);

// Update medications.ts: replace any /assets/protocols/... occurrences with normalized names
let meds = fs.readFileSync(medsFile, 'utf8');
meds = meds.replace(/\/assets\/protocols\/([^"'\)\s,]+)/g, (match, p1) => {
  // p1 is like Cardiac/C-1 AMI Fibrinolytic Checklist.pdf
  const parts = p1.split('/');
  const folder = parts[0];
  const file = parts.slice(1).join('/');
  const norm = normalizeName(file);
  return `/assets/protocols/${folder}/${norm}`;
});

fs.writeFileSync(medsFile, meds, 'utf8');
console.log('Updated', medsFile);
