const fs = require('fs');
const path = require('path');
const assetsProtocols = path.join(__dirname, '..', 'assets', 'protocols');
const outFile = path.join(__dirname, '..', 'src', 'data', 'protocolAssets.ts');

function walk(dir) {
  const results = [];
  const list = fs.readdirSync(dir, { withFileTypes: true });
  list.forEach((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walk(full));
    else if (entry.isFile()) results.push(full);
  });
  return results;
}

const files = walk(assetsProtocols).filter(f => /\.pdf$/i.test(f) || /\.jpg$/i.test(f) || /\.webp$/i.test(f));
let content = '// Auto-generated runtime map: pdfUrl -> required asset module\n// Regenerated by scripts/regenerateProtocolAssetsExact.js\n\nconst protocolAssets: { [k: string]: any } = {\n';
files.forEach(f => {
  const relUnderProtocols = path.relative(assetsProtocols, f).replace(/\\/g, '/');
  // url should be /assets/protocols/<rel>
  const pdfUrl = `/assets/protocols/${relUnderProtocols}`;
  const requirePath = `../../assets/protocols/${relUnderProtocols}`;
  content += `  "${pdfUrl}": require('${requirePath}'),\n`;
});
content += '};\n\nexport default protocolAssets;\n';
fs.writeFileSync(outFile, content, 'utf8');
console.log('Wrote', outFile);
